# Generated by Django 4.2.7 on 2023-12-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_votedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedusers',
            name='already_voted',
        ),
    ]
