# Generated by Django 4.2.7 on 2023-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_votedusers_already_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img_for_questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='main_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
